### ISSUE TITLE
Uncaught Error: Class 'GuzzleHttp\Client'

### ISSUE THREAD

**Issue by kkrieger85** [steverobbins/magescan#159]
Installation via 
```
mkdir -p ~/.n98-magerun/modules
git clone https://github.com/steverobbins/magescan ~/.n98-magerun/modules/magescan
```
also tried 
```
git clone https://github.com/steverobbins/magescan magescan
cd magescan
curl -sS https://getcomposer.org/installer | php
php composer.phar install
```

Error Message

```PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Client' not found in /home/kkrieger/.n98-magerun/modules/magescan/src/MageScan/Request.php:78
Stack trace:
#0 /home/kkrieger/.n98-magerun/modules/magescan/src/MageScan/Command/Scan/AbstractCommand.php(104): MageScan\Request->__construct('http://www.popu...', false)
#1 phar:///usr/local/bin/magerun/vendor/symfony/console/Command/Command.php(211): MageScan\Command\Scan\AbstractCommand->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/magerun/vendor/symfony/console/Application.php(853): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/magerun/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(MageScan\Command\Scan\AllCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Conso in /home/kkrieger/.n98-magerun/modules/magescan/src/MageScan/Request.php on line 78
```

php -v 
``` 
php -v                                                 
PHP 7.2.19-0ubuntu0.19.04.2 (cli) (built: Aug 13 2019 11:45:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.19.04.2, Copyright (c) 1999-2018, by Zend Technologies
```

php -m
```
[PHP Modules]
calendar
Core
ctype
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zlib

[Zend Modules]
Zend OPcache
```

**Comment by kkrieger85** [comment]
This only happens when I try to use the magerun command.

Using `php bin/magescan scan:all mysite.org` command runs fine
